### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by wojcik13** [gauravat16/CodeSalad#2]
Hi,
can U help with installation your judge on VPS with Debian 8?
TIA
Kindly regards c:

**Comment by gauravat16** [comment]
@wojcik13 Sure, Just point me to the step(s) you are having trouble with.

Also, this project is no longer maintained so it may have bugs and unfinished features :)

**Comment by wojcik13** [comment]
Can I replace tomcat with apache?

**Comment by gauravat16** [comment]
Do you mean Apache HTTP Server? Then No, Alphacode needs a java container.
